# Generated by Django 3.1.3 on 2023-12-06 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_auto_20230426_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='carrera',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='matricula',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
